"""Application constants."""

# Spaced Repetition Constants
INITIAL_INTERVAL_DAYS = 1
EXCELLENT_SCORE_THRESHOLD = 0.8
GOOD_SCORE_THRESHOLD = 0.6
EXCELLENT_MULTIPLIER = 2.5
GOOD_MULTIPLIER = 1.5
MAX_INTERVAL_DAYS = 90

# Quiz Constants
DEFAULT_QUESTIONS_PER_SESSION = 5
MIN_QUESTIONS_PER_SESSION = 3
MAX_QUESTIONS_PER_SESSION = 10

# Content Constants
MIN_TOPIC_LENGTH_WORDS = 100
MAX_TOPICS_PER_SYNC = 100

# Scheduler Constants
TEST_SCHEDULE_MINUTES = 5  # For testing purposes
